### ISSUE TITLE
Implement AddXXXForce for Bullet

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo#1476]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/1476)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
Related ODE [pull request #1456](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/1456)

**Comment by jeduardo211** [comment]
I am thinking about working on a series of PRs to implement or correct the implementation of the methods to add and set forces and torques in order to ensure that the behavior of theses methods is consistent across all physics engines, but I would like to ask two questions before starting to work on this:

1. Would such PRs be acceptable and able to be merged in the last version of Gazebo classic (v11)?
2. Is there any tests for these methods, I cannot find them in the physics directory, can anyone point me to their location?

@chapulina Are you be able to answer these two questions or can you point me to anyone who can answer them?

**Comment by scpeters** [comment]
> 1. Would such PRs be acceptable and able to be merged in the last version of Gazebo classic (v11)?

Yes! I would be happy to review these pull requests.

> 2. Is there any tests for these methods, I cannot find them in the physics directory, can anyone point me to their location?

There are related tests in [physics_link.cc](https://github.com/osrf/gazebo/blob/gazebo11/test/integration/physics_link.cc#L209-L218). If you update the logic in that linked code block you can enable the bullet tests, which should fail until the implementation is fixed

**Comment by scpeters** [comment]
fixed by #3255
