### ISSUE TITLE
gazebo9 crash Bug of ARIAC2019 gazebo environment

### ISSUE THREAD

**Issue by whathty** [osrf/gazebo#2880]
We are doing some automatic tests for some ariac2019 compitition project, when we changing config file of the  gear2019,we need close and restart ariac2019 gazebo environment many  times,But we  often meet a gazebo crash like this:

gzserver: /usr/include/boost/smart_ptr/enable_shared_from_this.hpp:51: boost::shared_ptr<X> boost::enable_shared_from_this<T>::shared_from_this() [with T = gazebo::transport::Node]: Assertion `p.get() == this' failed.

This error result gazebo spawn model service can not start, we do not know what’s cause this error,please help.thinks!

**Comment by chapulina** [comment]
This question is being cross-posted in several places:

* https://community.gazebosim.org/t/gazebo9-crash-error-for-ariac2019-gazebo-environment/731
* https://bitbucket.org/osrf/ariac/issues/189/ariac-gear2019-crash-bug
* https://answers.gazebosim.org/question/26096/gazebo-crash-when-restart-simulation-environment-of-ariac2019/
* https://answers.gazebosim.org/question/26095/gazebo-crash-when-restart-simulation-environment-of-ariac2019/

I'm going to close this one because it's not clear that this is a bug in Gazebo. Please don't flood the maintainers by posting the same question in several places. Post just one well explained question in the correct place and give people the time to answer.
