### ISSUE TITLE
Distributed Gazebo Classic simulation

### ISSUE THREAD

**Issue by JVMergulho** [osrf/gazebo#3355]
Is it possible to run a Gazebo Classic simulation distributed across more than one machine?

Currently I'm working on a project where we use ROS2 Humble integrated with Gazebo Classic. One of our goals is to distribute the Gazebo simulation so that the Gazebo world and each robot present on the scene is located in different hosts. 

However, I haven't found any Gazebo Classic documentation about distributed simulations.

**Comment by traversaro** [comment]
Hello @JVMergulho, please do not cross-post between issue trackers and official Q&A systems (in this case, https://robotics.stackexchange.com/questions/105111), thanks. If you think in some case it is appropriate to cross-post for some reason, at least cross-link the two posts, to avoid that people spend time to answer something that was already answered.

As the question was already answered in https://robotics.stackexchange.com/questions/105111, I think we can close the issue here, feel free to comment if you think it should be re-opened, thanks.
